// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RetroSpec.Infrastructure.DataAccess;

#nullable disable

namespace RetroSpec.MariaDb.Migrations
{
    [DbContext(typeof(RetroDbContext))]
    partial class RetroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RetroSpec.Core.BoardModels.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Boards", "Retro");
                });

            modelBuilder.Entity("RetroSpec.Core.BoardModels.Column", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id", "BoardId");

                    b.HasIndex("BoardId");

                    b.ToTable("Columns", "Retro");
                });

            modelBuilder.Entity("RetroSpec.Core.CardModels.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ColumnId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColumnId", "BoardId");

                    b.ToTable("Cards", "Retro");
                });

            modelBuilder.Entity("RetroSpec.Core.BoardModels.Column", b =>
                {
                    b.HasOne("RetroSpec.Core.BoardModels.Board", null)
                        .WithMany("Columns")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RetroSpec.Core.CardModels.Card", b =>
                {
                    b.HasOne("RetroSpec.Core.BoardModels.Column", null)
                        .WithMany()
                        .HasForeignKey("ColumnId", "BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RetroSpec.Core.BoardModels.Board", b =>
                {
                    b.Navigation("Columns");
                });
#pragma warning restore 612, 618
        }
    }
}
